CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
DATASET:
  DATASET: rellis
  NUM_CLASSES: 19
  ROOT: /home/ales/catkin_ws/src/traversability_estimation/data/Rellis_3D/
  TEST_SET: test.lst
  TRAIN_SET: train.lst
GPUS: (0,)
LOG_DIR: log
LOSS:
  BALANCE_WEIGHTS:
  - 0.4
  - 1
  OHEMKEEP: 131072
  OHEMTHRES: 0.9
  USE_OHEM: false
MODEL:
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      BLOCK: BOTTLENECK
      FUSE_METHOD: SUM
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      NUM_MODULES: 1
      NUM_RANCHES: 1
    STAGE2:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS:
      - 4
      - 4
      NUM_BRANCHES: 2
      NUM_CHANNELS:
      - 48
      - 96
      NUM_MODULES: 1
    STAGE3:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_BRANCHES: 3
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      NUM_MODULES: 4
    STAGE4:
      BLOCK: BASIC
      FUSE_METHOD: SUM
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_BRANCHES: 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      NUM_MODULES: 3
  NAME: seg_hrnet_ocr
  NUM_OUTPUTS: 2
  PRETRAINED: /home/ales/catkin_ws/src/traversability_estimation/config/weights/seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484/best.pth
OUTPUT_DIR: output
PRINT_FREQ: 10
TEST:
  BASE_SIZE: 1024
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  IMAGE_SIZE:
  - 1024
  - 512
  MULTI_SCALE: false
TRAIN:
  BASE_SIZE: 1920
  BATCH_SIZE_PER_GPU: 4
  BEGIN_EPOCH: 0
  DOWNSAMPLERATE: 1
  END_EPOCH: 484
  FLIP: true
  IGNORE_LABEL: 255
  IMAGE_SIZE:
  - 1024
  - 640
  LR: 0.001
  MOMENTUM: 0.9
  MULTI_SCALE: true
  NESTEROV: false
  OPTIMIZER: sgd
  RESUME: true
  SCALE_FACTOR: 16
  SHUFFLE: true
  WD: 0.0005
WORKERS: 4
