labels:
  0: "void"
  1: "dirt"
  3: "grass"
  4: "tree"
  5: "pole"
  6: "water"
  7: "sky"
  8: "vehicle"
  9: "object"
  10: "asphalt"
  12: "building"
  15: "log"
  17: "person"
  18: "fence"
  19: "bush"
  23: "concrete"
  27: "barrier"
  31: "puddle"
  33: "mud"
  34: "rubble"

color_map: # bgr
  0: [ 0, 0, 0 ]
  1: [ 0,255,0 ]
  3: [ 0,255,0 ]
  4: [ 255,0,0 ]
  5: [ 255,0,0 ]
  6: [ 255,0,0 ]
  7: [ 255,0,0 ]
  8: [ 255,0,0 ]
  9: [ 255,0,0 ]
  10: [ 0,255,0 ]
  12: [ 255,0,0 ]
  15: [ 255,0,0 ]
  17: [ 255,0,0 ]
  18: [ 255,0,0 ]
  19: [ 255,0,0 ]
  23: [ 255,0,0 ]
  27: [ 255,0,0 ]
  31: [ 0,255,0 ]
  33: [ 0,255,0 ]
  34: [ 0,255,0 ]