name: "traversability"
traversable_labels:
  1: "dirt"
  3: "grass"
  4: "tree"
  10: "asphalt"
  23: "concrete"
  31: "puddle"
  33: "mud"
  34: "rubble"
untraversable_labels:
  4: "tree"
  5: "pole"
  6: "water"
  8: "vehicle"
  9: "object"
  12: "building"
  15: "log"
  17: "person"
  18: "fence"
  19: "bush"
  27: "barrier"
color_map: # bgr
  0: [0, 255, 0]
  1: [0, 0, 255]
